[package]
name = "load_balancer"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }



[[bin]]
name = "server"
path = "src/bin/App/server.rs"
[[bin]]
name= "client"
path="src/bin/App/client.rs"